[package]
name = "simulated_annealing"
version = "0.1.0"
edition = "2024"

[dependencies]
plotters = "0.3.7"
rand = "0.9.1"
rand_distr = "0.5.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
