debug: lev.cpp
	g++ -Wall -Wextra -Wpedantic -Wshadow -Werror -std=c++17 -O0 -g lev.cpp -o lev.x

release: lev.cpp
	g++ -Wall -Wextra -Wpedantic -Wshadow -Werror -std=c++17 -O3 -DNDEBUG -march=native -mtune=native lev.cpp -o lev.x
