[workspace]
members = [
  "common",
  "pcazip",
  "pcaunzip",
]
resolver = "3"

[profile.release]
debug-assertions = false
opt-level = 3

[profile.dev]
debug-assertions = true
opt-level = 0

[profile.test]
debug-assertions = true
opt-level = 0
strip = "none"
overflow-checks = true
